### ISSUE TITLE
adding speech language?

### ISSUE THREAD

**Issue by kurt-o-sys** [mschmo/reveal-speech#1]
To make it work better in other languages, having the ability to set the langauge would be great:
```
recognition.lang = <config-lang>;
```

in webkit-speech, languages can be set like accept-language headers, so something like `"nl-BE, en-GB;0.8, fr-BE;0.7"` would work great as well (so it seems).

**Comment by mschmo** [comment]
I like that idea a lot! Just should maintain a default of the either the HTML lang attribute or user agent's language setting.

**Comment by mschmo** [comment]
Added in PR #2
